# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20171222_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='limit',
            new_name='guest_num',
        ),
        migrations.AddField(
            model_name='event',
            name='part_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
